---
- name: app | clone docker-compose repo
  git:
    repo: "{{ repo }}" 
    dest: /tmp/compose
    force: yes
  tags:
  - repo
  - compose

- name: app | create .env file
  copy: 
    dest: /tmp/compose/.env
    content: | 
      REDMINE_DB_USERNAME={{ redmine_db_user }}
      REDMINE_DB_PASSWORD={{ redmine_db_pass }}
      REDMINE_DB_DATABASE={{ redmine_db_name }}
      DB_HOST={{ db_host }}
      SECRET_KEY_BASE={{ secret_key_base }}
    mode: 0644
  tags:
  - envfile
  - compose

- name: app | run start script
  become: yes
  shell: /tmp/compose/bin/start 
  tags:
  - start
  - compose

# - name: app | run start script
#   become_user: "{{ redmine_user }}"
#   become: yes
#   script: 
#     cmd: /tmp/compose/bin/start